services:
  postgres:
    build: 
      context: .
      args:
        PG_IMAGE: ${PG_IMAGE:-postgres:latest}
    container_name: ${PG_CONTAINER_NAME:-pg-mock-time}
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      # Server LD_PRELOAD is handled by the image entrypoint (see Dockerfile)
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./test_mock_time.sql:/docker-entrypoint-initdb.d/99-test.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
